/// Parity test: the Dart on-device port must reproduce labeling.py exactly.
///
/// Two implementations of the same maths exist — labeling.py (training) and
/// risk_rules.dart + feature_window.dart (inference). If they drift, the model
/// is fed features unlike the ones it was trained on and the app quietly gets
/// worse with no error anywhere. This test pins the contract against
/// mlops/golden_vectors.json, regenerated by mlops/verify_dart_parity.py.
///
/// Run:  flutter test test/parity_test.dart
/// (Copy or symlink mlops/golden_vectors.json to app/test/golden_vectors.json.)
library parity_test;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:thermostat/core/feature_window.dart';
import 'package:thermostat/core/risk_rules.dart';

const tol = 1e-5;

void main() {
  late Map<String, dynamic> golden;

  setUpAll(() {
    final f = File('test/golden_vectors.json');
    expect(f.existsSync(), isTrue,
        reason: 'run mlops/verify_dart_parity.py and copy '
            'golden_vectors.json into app/test/');
    golden = jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
  });

  test('heat index and PAGASA banding match labeling.py', () {
    var checked = 0;
    for (final c in (golden['scalars'] as List).cast<Map<String, dynamic>>()) {
      if (c['kind'] != 'heat_index') continue;
      final hi = rothfuszHeatIndexC(
          (c['temp_c'] as num).toDouble(), (c['rh_pct'] as num).toDouble());
      expect(hi, closeTo((c['heat_index_c'] as num).toDouble(), tol),
          reason: 'HI(${c['temp_c']},${c['rh_pct']})');
      expect(pagasaRiskClass(hi), c['pagasa_class']);
      checked++;
    }
    expect(checked, greaterThan(0));
  });

  test('PSI and its banding match labeling.py', () {
    for (final c in (golden['scalars'] as List).cast<Map<String, dynamic>>()) {
      if (c['kind'] != 'psi') continue;
      final p = UserProfile(
        userId: 'G',
        ageYears: (c['age_years'] as num).toDouble(),
        heightCm: 170,
        weightKg: 70,
        restingHrBpm: (c['resting_hr'] as num).toDouble(),
      );
      expect(p.hrMax, closeTo((c['hr_max'] as num).toDouble(), tol));
      final psi = psiHeartRate((c['hr_bpm'] as num).toDouble(), p);
      expect(psi, closeTo((c['psi'] as num).toDouble(), tol));
      expect(psiRiskClass(psi), c['psi_class']);
    }
  });

  test('fusion rule matches labeling.py across every band combination', () {
    for (final c in (golden['scalars'] as List).cast<Map<String, dynamic>>()) {
      if (c['kind'] != 'fusion') continue;
      // Reconstruct a profile with the same BMI/age/CVD flags.
      final age = (c['age_years'] as num).toDouble();
      final bmi = (c['bmi'] as num).toDouble();
      const h = 170.0;
      final w = bmi * (h / 100) * (h / 100);
      final p = UserProfile(
        userId: 'G',
        ageYears: age,
        heightCm: h,
        weightKg: w,
        restingHrBpm: 60,
        cardiovascularCondition: c['cardiovascular'] as bool,
      );
      final got = fuseRisk(c['env_class'] as int, c['psi_class'] as int, p,
          spo2Desat: c['spo2_desat'] as bool);
      expect(got, c['risk_class'],
          reason: 'fusion ${c['profile']} env=${c['env_class']} '
              'psi=${c['psi_class']} desat=${c['spo2_desat']}');
    }
  });

  test('windowed features match labeling.py on a 90-minute series', () {
    final w = golden['window'] as Map<String, dynamic>;
    final fw = FeatureWindow();
    final t0 = DateTime.utc(2026, 4, 20, 11);
    for (final s in (w['samples'] as List).cast<Map<String, dynamic>>()) {
      fw.add(
        at: t0.add(Duration(minutes: s['t_offset_min'] as int)),
        compensatedAmbientC: (s['ambient_temp_c'] as num).toDouble(),
        humidityPct: (s['relative_humidity_pct'] as num).toDouble(),
        hrBpm: (s['heart_rate_bpm'] as num).toDouble(),
        spo2Pct: (s['spo2_pct'] as num).toDouble(),
      );
    }
    expect(fw.ready, isTrue, reason: '90 minutes should clear the 60-min warm-up');

    final feats = fw.features(
        ageYears: 30, bmi: 24.2, cardiovascular: false, heatIndexC: 0, psi: 0);
    final expected = (w['expected_features'] as Map<String, dynamic>);
    var compared = 0;
    expected.forEach((name, value) {
      if (value == null) return; // NaN in pandas — nothing to compare
      expect(feats.containsKey(name), isTrue, reason: 'missing feature $name');
      expect(feats[name], closeTo((value as num).toDouble(), 1e-4),
          reason: name);
      compared++;
    });
    expect(compared, greaterThan(20),
        reason: 'expected a substantial number of comparable features');
  });
}
